FROM alpine:3.8

RUN echo https://mirrors.ustc.edu.cn/alpine/v3.8/main > /etc/apk/repositories; \
    echo https://mirrors.ustc.edu.cn/alpine/v3.8/community >> /etc/apk/repositories;\
    echo "Asia/Shanghai" > /etc/timezone ;\
