package com.demo.dao;

import com.demo.entity.Address;
import com.demo.entity.AddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    long countByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    int deleteByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    @Delete({
        "delete from address",
        "where address_id = #{addressId,jdbcType=SMALLINT}"
    })
    int deleteByPrimaryKey(Short addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    @Insert({
        "insert into address (address_id, address, ",
        "address2, district, ",
        "city_id, postal_code, ",
        "phone, last_update, ",
        "location)",
        "values (#{addressId,jdbcType=SMALLINT}, #{address,jdbcType=VARCHAR}, ",
        "#{address2,jdbcType=VARCHAR}, #{district,jdbcType=VARCHAR}, ",
        "#{cityId,jdbcType=SMALLINT}, #{postalCode,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{lastUpdate,jdbcType=TIMESTAMP}, ",
        "#{location,jdbcType=BINARY})"
    })
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    List<Address> selectByExampleWithBLOBs(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    List<Address> selectByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "address_id, address, address2, district, city_id, postal_code, phone, last_update, ",
        "location",
        "from address",
        "where address_id = #{addressId,jdbcType=SMALLINT}"
    })
    @ResultMap("com.demo.dao.AddressMapper.ResultMapWithBLOBs")
    Address selectByPrimaryKey(Short addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Address record, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Address record, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Address record, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    @Update({
        "update address",
        "set address = #{address,jdbcType=VARCHAR},",
          "address2 = #{address2,jdbcType=VARCHAR},",
          "district = #{district,jdbcType=VARCHAR},",
          "city_id = #{cityId,jdbcType=SMALLINT},",
          "postal_code = #{postalCode,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP},",
          "location = #{location,jdbcType=BINARY}",
        "where address_id = #{addressId,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKeyWithBLOBs(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    @Update({
        "update address",
        "set address = #{address,jdbcType=VARCHAR},",
          "address2 = #{address2,jdbcType=VARCHAR},",
          "district = #{district,jdbcType=VARCHAR},",
          "city_id = #{cityId,jdbcType=SMALLINT},",
          "postal_code = #{postalCode,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where address_id = #{addressId,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKey(Address record);
}